### ISSUE TITLE
Failed to pub get this package

### ISSUE THREAD

**Issue by musfique113** [RafatMeraz/network_caller#1]
**Issue: Error during Dependency Adding **

**Description:**
I'm encountering an error during the dependency adding phase with the following code snippet:

```yaml
network_caller:
  git:
    url: git://github.com/RafatMeraz/network_caller.git
    ref: version
```

**Suggested Fix:**
To resolve this issue, I recommend updating the code as follows:

```yaml
network_caller:
  git:
    url: https://github.com/RafatMeraz/network_caller.git
    ref: master
```
